// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_add from "./routes/api/add.ts";
import * as $api_delete from "./routes/api/delete.ts";
import * as $api_list from "./routes/api/list.ts";
import * as $api_truncate from "./routes/api/truncate.ts";
import * as $api_update from "./routes/api/update.ts";
import * as $api_websocket from "./routes/api/websocket.ts";
import * as $index from "./routes/index.tsx";
import * as $AddData from "./islands/AddData.tsx";
import * as $ClearDatas from "./islands/ClearDatas.tsx";
import * as $DataList from "./islands/DataList.tsx";
import * as $WebsocketStatus from "./islands/WebsocketStatus.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/add.ts": $api_add,
    "./routes/api/delete.ts": $api_delete,
    "./routes/api/list.ts": $api_list,
    "./routes/api/truncate.ts": $api_truncate,
    "./routes/api/update.ts": $api_update,
    "./routes/api/websocket.ts": $api_websocket,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AddData.tsx": $AddData,
    "./islands/ClearDatas.tsx": $ClearDatas,
    "./islands/DataList.tsx": $DataList,
    "./islands/WebsocketStatus.tsx": $WebsocketStatus,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
